### ISSUE TITLE
book-search를 이용한 등록된 책 검색

### ISSUE THREAD

**Issue by jjongbumeee** [jjongbumeee/magicSora#11]
book-search component 를 이용하여

1. remote server로 book-search.text를 전송
2. remote server에서 DB에 SQL 질의
3. 질의 결과를 frontend로 전송
4. frontend에서 사용자 UI로 표시

**Comment by lee20h** [comment]
1. FE단 책 제목 전송
2. BE단 DB 조회 질의
3. BE단 해당 책들 전송
4. FE단 컴포넌트에 알맞게 표시

**Comment by jjongbumeee** [comment]
1 ~ 4 해결 완료
