### ISSUE TITLE
등록된 책 삭제하기

### ISSUE THREAD

**Issue by jjongbumeee** [jjongbumeee/magicSora#14]
관리자 또는 등록한 사용자(이 부분은 어떻게 처리하면 좋을지 comment 부탁드립니다.)가
정식 등록(승인완료) 또는 가등록(등록 신청했지만 관리자가 승인하지 않은 책) 된 책의
삭제, 판매 철회 요청 기능이 필요합니다.

**Comment by lee20h** [comment]
정식 등록시에 vue에서 버튼을 달아 데이터베이스 img부분을 가져와
node.js fs 모듈로 unlink 시킵니다. 이후 데이터베이스에서도 해당 테이블을 drop합니다.
