### ISSUE TITLE
앞으로..

### ISSUE THREAD

**Issue by lee20h** [jjongbumeee/magicSora#9]
### **앞으로 해야 할  일**

_DB 원격 접근 - **frontend에서 주소 수정** (완)_

DB검색을 통한 책 검색
UI 및 디자인 개선

### 관리자 로그인 구현
- DB제거를 통한 책 목록 제거
- 책 등록 후 관리자의 승인 하에 목록에 추가

### 수혁

- [ **readme 작성**]

**Comment by jjongbumeee** [comment]
각각의 서버로 host, port, mysql user, password를 지정하도록 설정 및 github .gitignore 설정완료
그러나 여전히 DOMException error 발생으로 /book_tbl로의 접근이 원활하지 않은 상황임

**Comment by lee20h** [comment]
DB원격 접근 (완)
